import html,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; A=ROOT/'local/uckk/atlas'
S=json.loads((A/'ucc_course_syllabi.json').read_text()); W={x['work_ref']:x for x in json.loads((A/'ucc_mediatheque_reference_registry.json').read_text())['works']}; C=json.loads((A/'ucc_curriculum_registry.json').read_text())
e=html.escape
out=['''<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>UCC · Plans et lectures</title>
<style>:root{--ink:#213a34;--paper:#faf8f2;--line:#d9ded5}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:#25332f;font:16px/1.65 system-ui,sans-serif}header{background:var(--ink);color:white;padding:48px max(24px,calc((100vw - 1120px)/2))}h1{font:clamp(2rem,5vw,3.8rem)/1.1 Georgia,serif;margin:16px 0}h2,h3{font-family:Georgia,serif}main{max-width:1120px;margin:32px auto;padding:0 24px}a{color:#236c57}header p{max-width:800px;color:#e0e8df}.kicker{letter-spacing:.18em;text-transform:uppercase;font-size:.8rem}.metrics{display:flex;gap:28px;flex-wrap:wrap}.metrics strong{font-size:1.5rem}.toolbar{display:flex;gap:16px;flex-wrap:wrap;padding:20px;background:#edf1e9;border:1px solid var(--line);margin:24px 0}label{display:grid;gap:4px;flex:1;min-width:230px}input,select,button{font:inherit;padding:10px;border:1px solid #9bac9f;border-radius:4px;background:white}summary{cursor:pointer;font-size:1.05rem;font-weight:650;padding:20px}details{border:1px solid var(--line);border-radius:6px;background:white;margin:12px 0}details[open] summary{border-bottom:1px solid var(--line)}.content{padding:4px 24px 24px}.reading{border-left:3px solid #a2b89e;padding:8px 18px;margin:18px 0}.note{background:#f5f0dd;padding:14px;font-size:.9rem}.meta{color:#5b6a62;font-size:.88rem}li{margin:6px 0}.question{font-size:1.15rem}.tabs a{display:inline-block;margin:0 20px 12px 0}.reference{padding:16px 0;border-bottom:1px solid var(--line)}[hidden]{display:none!important}footer{margin:40px 0;color:#5b6a62}@media print{header{background:white;color:black}.toolbar,.tabs{display:none}details{break-inside:avoid}header p{color:black}}</style>
<header><div class="kicker">Univers-Cité chrétienne · 28 septembre 2026</div><h1>Lire. Comparer.<br>Argumenter.</h1><p>Un parcours historique dans les sources chrétiennes et catholiques, ouvert à la confrontation des idées. Onze Voies, des lectures localisées et des travaux qui rendent le raisonnement vérifiable.</p><div class="metrics"><span><strong>110</strong> plans</span><span><strong>132</strong> fiches</span><span><strong>338</strong> liens choisis</span></div></header><main>
<p class="note"><strong>Statut de cette édition :</strong> plans de séminaire proposés, à relire et à valider. Les repères de lecture demandent collation dans l’édition utilisée. Ce catalogue ne crée ni inscription Moodle, ni crédit, ni reconnaissance académique.</p>
<nav class="tabs"><a href="#plans">Plans des cours</a><a href="#references">Catalogue des références</a><a href="#limites">Lacunes et méthode</a></nav><section id="plans"><h2>Choisir un parcours</h2><p>Socle conseillé : Écriture (THE-101), Trinité (THE-103), Incarnation (THE-104), sacrements (THE-106), histoire ecclésiale (THE-108), vie spirituelle (THE-109), méthode (OEU-105), argumentation (PHI-101).</p><div class="toolbar"><label>Rechercher un cours<input id="search" type="search" placeholder="Trinité, dette, archives…"></label><label>Voie<select id="path"><option value="">Toutes les Voies</option>''']
for p in C['pathways']:out.append(f'<option value="{e(p["pathway_id"])}">{e(p["title"])}</option>')
out.append('</select></label></div><p id="count" role="status" aria-live="polite">110 cours</p>')
for p in S['courses']:
 out.append(f'<details class="course" id="{e(p["course_id"])}" data-path="{e(p["pathway_id"])}"><summary>{e(p["course_id"])} · {e(p["title"])}</summary><div class="content"><p class="question">{e(p["central_question"])}</p><p class="meta">{p["estimated_hours"]} heures indicatives · {e(p["level"])} · sans crédit</p><p>Prérequis conseillés : '+(', '.join(f'<a href="#{e(x)}">{e(x)}</a>' for x in p['prerequisites']) or 'aucun')+'</p><h3>Objectifs</h3><ul>'+''.join('<li>'+e(x)+'</li>' for x in p['objectives'])+'</ul><h3>Lectures choisies</h3>')
 for m in p['readings']:
  w=W[m['media_ref']]
  out.append(f'<div class="reading"><strong>{e(w["title"])}</strong><p class="meta">{e(w.get("creator","Auteur à préciser"))} · {e(w["language"])} · {e(m["role"])}</p><p><b>Passage :</b> {e(m["passage"])}</p><p>{e(m["rationale"])}</p><p class="meta">{e(w.get("teachingnote","Édition et traduction à vérifier."))}</p><a href="{e(w["sourceurl"],quote=True)}" target="_blank" rel="noopener noreferrer">Consulter la source</a><p class="meta">Lecture proposée ; repère à collationner. Édition : {e(m["edition_status"])}.</p></div>')
 out.append('<h3>Cinq séances</h3><ol>')
 for x in p['sessions']:out.append(f'<li><strong>{e(x["title"])}</strong><br>{e(x["activity"])}<br><span class="meta">Production : {e(x["output"])}</span></li>')
 out.append('</ol><h3>Évaluation</h3><p>'+e(p['assessment']['task'])+'</p><p>'+e(p['assessment']['deliverable'])+'</p><ul>'+''.join(f'<li>{e(x["criterion"])} : {x["weight"]} %</li>' for x in p['assessment']['rubric'])+'</ul><p>'+e(p['assessment']['integrity'])+'</p><div class="note"><b>Contexte et limites</b><ul>'+''.join('<li>'+e(x)+'</li>' for x in p['contextual_cautions'])+'</ul></div></div></details>')
out.append('</section><section id="references"><h2>Références et cours associés</h2><p>Les fiches comprennent des œuvres, éditions et extraits. Une référence en réserve n’est pas une lecture prescrite. Aucun droit de copie n’est déduit de sa présence ici.</p>')
for w in W.values():
 out.append('<details class="reference"><summary>'+e(w['title'])+'</summary><div class="content"><p>'+e(w['citation'])+'</p><p>'+e(w.get('teachingnote','Édition, traduction et conditions de réutilisation à vérifier.'))+'</p><p class="meta">Langue : '+e(w['language'])+' · droits : '+e(w['rightsstatus'])+' · '+e(w['reference_review']['status'])+'</p><p><a href="'+e(w['sourceurl'],quote=True)+'" rel="noopener noreferrer" target="_blank">Source externe</a></p><p>'+(' · '.join('<a href="#'+e(x)+'">'+e(x)+'</a>' for x in w['metadata']['course_refs']) or 'Réserve documentaire — aucun cours associé actuellement.')+'</p></div></details>')
out.append('</section><section id="limites"><h2>Lacunes explicites</h2><ul>'+''.join('<li>'+e(x)+'</li>' for x in S['open_gaps'])+'</ul><p>Fonds principal : œuvres jusqu’en 1926 inclusivement. Exceptions : Pierre Teilhard de Chardin, <i>Fratelli tutti</i> et <i>Le Dieu cosmique</i>. Les compléments UCC ne sont pas attribués à la bibliographie de ce dernier.</p></section><footer>Version de travail éditoriale · Les sources restent hébergées par leurs fournisseurs.</footer></main>')
out.append('''<script>const rows=[...document.querySelectorAll('.course')],q=document.querySelector('#search'),path=document.querySelector('#path');const norm=s=>s.normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toLowerCase();function filter(){let n=0;for(const r of rows){r.hidden=!!((path.value&&r.dataset.path!==path.value)||(q.value&&!norm(r.textContent).includes(norm(q.value))));if(!r.hidden)n++}document.querySelector('#count').textContent=n+' cours'}q.addEventListener('input',filter);path.addEventListener('change',filter);function reveal(){const el=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(el&&el.matches('.course')){q.value='';path.value='';filter();el.open=true;el.scrollIntoView()}}window.addEventListener('hashchange',reveal);reveal();</script></html>''')
(ROOT/'docs/ucc/CATALOGUE_UCC.html').write_text(''.join(out))
